site_name: ChesslaBlab
site_url: https://chesslablab.github.io/website/
theme:
  name: mkdocs
nav:
  - Home: index.md
  - Installation: installation.md
  - Website Architecture: website-architecture.md
  - WebSocket Connection: websocket-connection.md
  - Blog: blog.md
  - HTML Iframes: html-iframes.md
